# pod has mixed containers, some allowed and some not allowed to receive env vars from node labels
apiVersion: v1
kind: Pod
metadata:
  name: pod-mixed
  namespace: samples
  labels:
    app: pod-mixed
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: true
    runAsUser: 99
  containers:
    - name: ingester
      image: busybox
      envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secrets
      command: ["/bin/sh"]
      args: ["-c", "env"]
    - name: store-gateway
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "env"]
    - name: compactor
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "env"]
      envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secrets
